/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_diplab_activiti_smoke_RpiSmokeReceiver */

#ifndef _Included_com_diplab_activiti_smoke_RpiSmokeReceiver
#define _Included_com_diplab_activiti_smoke_RpiSmokeReceiver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_diplab_activiti_smoke_RpiSmokeReceiver
 * Method:    getSmokePpm
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_diplab_activiti_smoke_RpiSmokeReceiver_getSmokePpm
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_diplab_activiti_temperature_RpiTemperatureReceiver */

#ifndef _Included_com_diplab_activiti_temperature_RpiTemperatureReceiver
#define _Included_com_diplab_activiti_temperature_RpiTemperatureReceiver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_diplab_activiti_temperature_RpiTemperatureReceiver
 * Method:    getTemperatureCelsius
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_diplab_activiti_temperature_RpiTemperatureReceiver_getTemperatureCelsius
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
